Repository gryffon/ringteki, pull requests merged in 2018-02, with the labels that each got.

#1627 Fixed discard setup for tests
  test/helpers/deckbuilder.js
  test/helpers/integrationhelper.js
  test/helpers/playerinteractionwrapper.js
Labels: tests

#1623 Stop an error caused by hitting 0 honor in a single player game
  server/game/game.js
Labels: bug

#1624 Talisman of the Sun bugfix
  server/game/cards/02.6-MotE/TalismanOfTheSun.js
Labels: bug

#1625 Perfect Gift bugfix
  server/game/cards/01-Core/ThePerfectGift.js
Labels: bug

#1626 Refactor setupAbilities test for all cards
  test/server/cards/cancreatecards.spec.js
Labels: tests

#1630 Brash Samurai bugfix
  server/game/cards/01-Core/BrashSamurai.js
Labels: bug

#1631 Bug fixes for Events
  server/game/Events/Event.js
  server/game/Events/EventWindow.js
  server/game/Events/InitiateAbilityEventWindow.js
  server/game/Events/LeavesPlayEvent.js
  server/game/Events/ThenEventWindow.js
  server/game/cards/02.3-ItFC/BayushiKachiko.js
  server/game/game.js
  test/server/gamesteps/eventwindow.spec.js
Labels: bug

#1628 Cavalry Reserve test
  test/server/cards/01-Core/CavalryReserves.spec.js
Labels: tests

#1635 Make discarding in regroup optional
  server/game/gamesteps/regroupphase.js
Labels: bug

#1653 Add MountaintopStatuary.spec.js
  test/helpers/integrationhelper.js
  test/server/cards/02.4-TCT/MountaintopStatuary.spec.js
Labels: tests

#1641 Take control bugfix
  server/game/game.js
  test/server/cards/01-Core/Blackmail.spec.js
Labels: bug

#1568 Rework the way persistent effects generate their target lists
  server/game/effect.js
  server/game/effectengine.js
  server/game/game.js
  test/server/effect.spec.js
  test/server/effectengine.spec.js
Labels: Experimental code, bug

#1642 Add additional checks to allowGameAction
  server/game/drawcard.js
  server/game/provincecard.js
Labels: bug

#1638 Refactor thenEvents
  server/game/Events/Event.js
  server/game/Events/EventBuilder.js
  server/game/Events/EventWindow.js
  server/game/Events/ThenEventWindow.js
  server/game/cards/02.3-ItFC/BayushiKachiko.js
  server/game/cards/02.3-ItFC/TestOfCourage.js
  server/game/game.js
  test/server/cards/02.3-ItFC/BayushiKachiko.spec.js
Labels: bug
