Repository gryffon/ringteki, pull requests merged in 2019-06, with the labels that each got.

#3224 Fix for Hantei/DyH interaction
  server/game/AbilityTargets/AbilityTargetAbility.js
  server/game/AbilityTargets/AbilityTargetCard.js
  server/game/AbilityTargets/AbilityTargetRing.js
  server/game/AbilityTargets/AbilityTargetSelect.js
  server/game/AbilityTargets/AbilityTargetToken.js
  server/game/baseability.js
  server/game/cards/06-CotE/DefendYourHonor.js
  test/server/cards/06-CotE/HanteiXXXVIII.spec.js
Labels: bug

#3229 Mirumoto Hitomi chat bugfix
  server/game/cards/06-CotE/MirumotoHitomi.js
Labels: bug

#3231 Cancel Action bugfix
  server/game/GameActions/CancelAction.ts
Labels: bug

#3244 Bugfix for RandomDiscardAction
  server/game/GameActions/RandomDiscardAction.ts
  test/server/cards/01-Core/StewardOfLaw.spec.js
  test/server/cards/04.2-TL/KuniYori.spec.js
  test/server/cards/04.4-TEaF/HiddenMoonDojo.spec.js
Labels: bug

#3227 Fix Hida Kisada bug
  server/game/cards/01-Core/HidaKisada.js
  test/server/cards/01-Core/HidaKisada.spec.js
Labels: bug

#3257 New Feature - Card Stats Popup
  client/GameBoard.jsx
  client/GameComponents/Card.jsx
  client/GameComponents/CardStats.jsx
  client/GameComponents/GameConfiguration.jsx
  client/Profile.jsx
  less/cardStats.less
  less/cards.less
  less/site.less
  server/game/drawcard.js
  server/settings.js
Labels: UI/client, enhancement

#3228 Bugfix - Feral Ningyo
  server/game/GameActions/DelayedEffectAction.ts
  server/game/cards/04.2-TL/FeralNingyo.js
  server/game/gamechat.js
  test/server/cards/04.2-TL/FeralNingyo.spec.js
Labels: bug

#3253 Bugfix - Alibi Artist
  server/game/cards/05-UotE/AlibiArtist.js
  test/server/cards/05-UotE/AlibiArtist.spec.js
Labels: bug

#3258 Bugfix - Hidden Moon Dojo chat messages
  server/game/cards/04.4-TEaF/HiddenMoonDojo.js
  test/server/cards/04.4-TEaF/HiddenMoonDojo.spec.js
Labels: bug

#3261 Bugfix - Shinjo Tatsuo to target himself correctly
  server/game/cards/01-Core/ShinjoTatsuo.js
  test/server/cards/01-Core/IdeTrader.spec.js
  test/server/cards/01-Core/ShinjoTatsuo.spec.js
Labels: bug

#3262 Bugfix - Infiltrator empty deck
  server/game/cards/04.3-TFW/Infiltrator.js
  test/server/cards/04.1-BotK/HeartlessIntimidator.spec.js
  test/server/cards/04.3-TFW/Infiltrator.spec.js
Labels: bug

#3271 Gained abilities chat messages
  server/game/CardAbility.js
  server/game/Effects/GainAbility.js
  test/server/card/CardAbility.displayMessage.spec.js
  test/server/cards/01-Core/DuelistTraining.spec.js
  test/server/cards/01-Core/TogashiYokuni.spec.js
  test/server/cards/02.6-MotE/IllustriousPlagiarist.spec.js
  test/server/cards/04.1-BotK/HirumaOutpost.spec.js
  test/server/cards/04.4-TEaF/Ofushikai.spec.js
  test/server/cards/06-CotE/TrueStrikeKenjutsu.spec.js
Labels: enhancement

#3275 Bugfix - improved chat messages for dispatch
  server/game/cards/04.5-AaN/Dispatch.js
  test/server/cards/04.5-AaN/Dispatch.spec.js
Labels: bug

#3272 Bugfix - Add null checks
  server/game/AbilityTargets/AbilityTargetSelect.js
  server/game/cards/01-Core/Rebuild.js
  server/game/cards/01-Core/ShamefulDisplay.js
Labels: bug

#3281 Byoyomi - fixes and additional options
  client/NewGame.jsx
  client/PendingGame.jsx
  server/game/Clocks/Byoyomi.js
  server/game/Clocks/Clock.js
  server/game/Clocks/ClockSelector.js
  server/game/game.js
  server/game/gamesteps/uiprompt.js
  server/game/player.js
  test/server/gamesteps/initiateconflictprompt.spec.js
  test/server/gamesteps/menuprompt.spec.js
  test/server/gamesteps/playerorderprompt.spec.js
  test/server/gamesteps/selectcardprompt.spec.js
  test/server/gamesteps/uiprompt.spec.js
Labels: bug, enhancement
