Repository gryffon/ringteki, pull requests merged in 2019-07, with the labels that each got.

#3308 Bugfixes - FGG and Mirror & GU
  server/game/GameActions/ResolveAbilityAction.ts
  server/game/cards/04.1-BotK/TheMirrorsGaze.js
  server/game/cards/09.1-FtE/GreaterUnderstanding.js
  test/server/cards/04.1-BotK/TheMirrorsGaze.spec.js
Labels: bug

#3307 Byoyomi - new style clock and clock popup
  client/GameComponents/Clock.jsx
  client/GameComponents/ClockPopup.jsx
  client/GameComponents/PlayerStatsBox.jsx
  less/gameboard.less
  less/gameboard/clock-popup.less
  server/game/Clocks/Byoyomi.js
  server/game/Clocks/ChessClock.js
  server/game/Clocks/Clock.js
  server/game/Clocks/Hourglass.js
  server/game/Clocks/Timer.js
Labels: enhancement

#3312 Bugfix - A Perfect Cut chat message
  server/game/cards/09.1-FtE/APerfectCut.js
  test/server/cards/09.1-FtE/APerfectCut.spec.js
Labels: bug

#3319 Bugfix - Zentaro
  client/HowToPlay.jsx
  server/game/PlayDisguisedCharacterAction.js
  server/game/baseability.js
  server/game/chatcommands.js
  server/game/game.js
  test/server/cards/09.1-FtE/AkodoZentaro.spec.js
Labels: bug

#3357 Bugfix - Various recent crashes
  server/game/GameObject.js
  server/game/basecard.ts
  server/game/cards/01-Core/Breakthrough.js
  server/game/cards/07-WotW/TradingOnTheSandRoad.js
Labels: bug

#3358 Feature - Icon for hand size
  client/GameComponents/PlayerStatsBox.jsx
  less/gameboard/player-stats.less
  public/img/conflictcard.png
  test/client/GameComponents/PlayerStatsBox.spec.jsx
Labels: UI/client, enhancement

#3364 Bugfix - Fate from rings
  server/game/gamesteps/conflict/conflictflow.js
  test/server/integration/conflictphase.spec.js
Labels: bug

#3366 Azunami bugfix
  server/game/cards/04.4-TEaF/AsakoAzunami.js
Labels: bug
